use std::{fs::File, path::Path};

use uasset::{AssetHeader, PackageFlags};

/// `assets/UE51/Maps/NewMap.umap` is a real, unmodified Unreal Engine 5.1 level (`.umap`) file.
/// It is the default empty level generated by the editor's "File > New Level" command, taken from
/// the MIT-licensed https://github.com/Megafunk/MassSample project (Content/NewMap.umap).
///
/// `.umap` files share the exact same `FPackageFileSummary` header format as `.uasset` files, so
/// `AssetHeader::new` does not need any `.umap`-specific handling: this test locks in that a real
/// world/level package parses correctly, including the `ContainsMap` package flag.
#[test]
fn loading_umap() {
    let path = "assets/UE51/Maps/NewMap.umap";
    let header = AssetHeader::new(File::open(path).unwrap()).unwrap();

    assert_eq!(header.package_name, "/Game/NewMap");
    assert_eq!(
        header.package_flags & PackageFlags::ContainsMap as u32,
        PackageFlags::ContainsMap as u32,
        "level packages (.umap) are expected to have the ContainsMap package flag set"
    );

    assert!(
        header.names.iter().any(|name| name == "/Game/NewMap"),
        "Missing package name in names"
    );
    assert!(
        header.names.iter().any(|name| name == "PersistentLevel"),
        "Missing PersistentLevel in names"
    );

    // Make sure we can follow references out of the map, just like we can for a regular asset.
    assert!(
        header
            .package_import_iter()
            .any(|import| import == "/Script/Engine"),
        "Expected an import referencing /Script/Engine"
    );

    // The map should have at least one export, and one of them should be the World itself,
    // named after the fixture file (matching Unreal's convention of naming the level's World
    // object after the package/file name).
    assert!(!header.exports.is_empty(), "Expected at least one export");
    let map_name = Path::new(path)
        .file_stem()
        .and_then(|stem| stem.to_str())
        .expect("Fixture path should have a valid file stem");
    let world_name_index = header
        .find_name(map_name)
        .expect("Missing the map's own name in the name table");
    assert!(
        header
            .exports
            .iter()
            .any(|export| export.object_name == world_name_index),
        "Expected an export named after the map itself"
    );
}
